# Generated by Django 3.1.4 on 2020-12-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('hobby', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='users/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField()),
            ],
        ),
    ]